<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.hfxr8GS' shared service.

return $this->privates['.service_locator.hfxr8GS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\HomeController::index' => ['privates', '.service_locator.zf96HF0', 'get_ServiceLocator_Zf96HF0Service.php', true],
    'App\\Controller\\PropertyController::show' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
    'App\\Controller\\HomeController:index' => ['privates', '.service_locator.zf96HF0', 'get_ServiceLocator_Zf96HF0Service.php', true],
    'App\\Controller\\PropertyController:show' => ['privates', '.service_locator.N38ovWA', 'get_ServiceLocator_N38ovWAService.php', true],
], [
    'App\\Controller\\HomeController::index' => '?',
    'App\\Controller\\PropertyController::show' => '?',
    'App\\Controller\\HomeController:index' => '?',
    'App\\Controller\\PropertyController:show' => '?',
]);
