<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCPUIWRE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCPUIWRE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCPUIWRE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCPUIWRE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCPUIWRE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CPUIWRE',
    'container.build_id' => '73f6c5c1',
    'container.build_time' => 1560680000,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCPUIWRE');
