<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFO9QlxB\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFO9QlxB/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFO9QlxB.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFO9QlxB\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFO9QlxB\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FO9QlxB',
    'container.build_id' => '93c506ca',
    'container.build_time' => 1563020538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFO9QlxB');
