<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZvtZMkY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZvtZMkY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZvtZMkY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZvtZMkY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZvtZMkY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZvtZMkY',
    'container.build_id' => '1f4067de',
    'container.build_time' => 1562756301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZvtZMkY');
